services:
  pocketbase:
    build:
      context: ./pocketbase
      dockerfile: Dockerfile
    container_name: pocketbase
    ports:
      - "8090:8090"
    volumes:
      - pb_data:/pb/pb_data
      - ./pocketbase/pb_migrations:/pb/pb_migrations
      - ./pocketbase/pb_hooks:/pb/pb_hooks
    restart: unless-stopped

  frontend:
    build: .
    container_name: tanstack-frontend
    ports:
      - "6968:80"
    restart: unless-stopped

volumes:
  pb_data:
